import { join } from 'node:path';
import { readdir } from 'node:fs/promises';
const dir = import.meta.dirname;
const flags = [
	'--target=wasm32-unknown-unknown',
	'-O3',
	'-flto',
	'-ffreestanding',
	'-fno-builtin',
	'-nostdlib',
	'-std=c11',
	'-I',
	'include',
	'-Wl,--no-entry',
	'-Wl,--export-memory',
	'-Wl,--initial-memory=16777216',
	'-Wl,--max-memory=16777216',
	'-Wl,-z,stack-size=262144',
	'-Wl,--strip-all'
];
const command = [
	Bun.env.CLANG ?? 'clang',
	...flags,
	join(dir, 'bridge.c'),
	join(dir, 'vendor/decode.c'),
	join(dir, 'vendor/crctab.c'),
	'-o',
	join(dir, 'decoder.wasm')
];
const p = Bun.spawn(command, { cwd: dir, stdout: 'inherit', stderr: 'inherit' });
if ((await p.exited) !== 0) throw new Error('WASM compilation failed');
const bytes = new Uint8Array(await Bun.file(join(dir, 'decoder.wasm')).arrayBuffer());
const module = new WebAssembly.Module(bytes);
if (WebAssembly.Module.imports(module).length) throw new Error('WASM must have no host imports');
await Bun.write(
	join(dir, '../src/wasm/bytes.ts'),
	`// Generated by wasm/build.ts; lbzip2 source and GPL license are in wasm/vendor/.\nexport const WASM_BASE64 =\n\t'${Buffer.from(bytes).toString('base64')}';\n`
);
const sourceHashes: Record<string, string> = {};
for (const file of [
	'bridge.c',
	...(await readdir(join(dir, 'vendor')).then(files => files.filter(f => /\.[ch]$/.test(f)).map(f => `vendor/${f}`))),
	...['assert.h', 'errno.h', 'inttypes.h', 'stdlib.h', 'string.h', 'arpa/inet.h'].map(f => `include/${f}`)
]) {
	sourceHashes[file] = new Bun.CryptoHasher('sha256')
		.update(await Bun.file(join(dir, file)).arrayBuffer())
		.digest('hex');
}
const version = Bun.spawn([Bun.env.CLANG ?? 'clang', '--version'], { stdout: 'pipe' });
const compiler = await new Response(version.stdout).text();
if ((await version.exited) !== 0) throw new Error('Unable to record compiler version');
await Bun.write(
	join(dir, 'build.json'),
	JSON.stringify(
		{
			upstream: 'https://github.com/kjn/lbzip2',
			revision: '724352c0495904ab16e33817fae85b262f319318',
			bytes: bytes.length,
			sha256: new Bun.CryptoHasher('sha256').update(bytes).digest('hex'),
			flags,
			compiler,
			sourceHashes
		},
		null,
		'\t'
	) + '\n'
);
console.log(`Built ${bytes.length} bytes of self-contained WASM`);
