import { join } from 'node:path';
import { readdir } from 'node:fs/promises';
const dir = import.meta.dirname;
const flags = [
	'--target=wasm32-unknown-unknown',
	'-O3',
	'-flto',
	'-ffreestanding',
	'-fno-builtin',
	'-nostdlib',
	'-std=c11',
	'-I',
	'include',
	'-Wl,--no-entry',
	'-Wl,--export-memory',
	'-Wl,-z,stack-size=262144',
	'-Wl,--strip-all'
];
const sourceHashes: Record<string, string> = {};
for (const file of [
	'bridge.c',
	'encoder-bridge.c',
	...(await readdir(join(dir, 'vendor')).then(files => files.filter(f => /\.[ch]$/.test(f)).map(f => `vendor/${f}`))),
	...['assert.h', 'errno.h', 'inttypes.h', 'stdlib.h', 'string.h', 'arpa/inet.h'].map(f => `include/${f}`)
]) {
	sourceHashes[file] = new Bun.CryptoHasher('sha256')
		.update(await Bun.file(join(dir, file)).arrayBuffer())
		.digest('hex');
}
const version = Bun.spawn([Bun.env.CLANG ?? 'clang', '--version'], { stdout: 'pipe' });
const compiler = await new Response(version.stdout).text();
if ((await version.exited) !== 0) throw new Error('Unable to record compiler version');
for (const target of [
	{
		name: 'decoder',
		sources: ['bridge.c', 'vendor/decode.c', 'vendor/crctab.c'],
		memory: 16777216,
		manifest: 'build.json',
		embedded: 'bytes.ts'
	},
	{
		name: 'encoder',
		sources: ['encoder-bridge.c', 'vendor/divbwt.c', 'vendor/crctab.c'],
		memory: 8388608,
		manifest: 'encoder-build.json',
		embedded: 'encoder-bytes.ts'
	}
]) {
	const targetFlags = [...flags, `-Wl,--initial-memory=${target.memory}`, `-Wl,--max-memory=${target.memory}`];
	const command = [
		Bun.env.CLANG ?? 'clang',
		...targetFlags,
		...target.sources.map(file => join(dir, file)),
		'-o',
		join(dir, `${target.name}.wasm`)
	];
	const p = Bun.spawn(command, { cwd: dir, stdout: 'inherit', stderr: 'inherit' });
	if ((await p.exited) !== 0) throw new Error(`${target.name} WASM compilation failed`);
	const bytes = new Uint8Array(await Bun.file(join(dir, `${target.name}.wasm`)).arrayBuffer());
	if (WebAssembly.Module.imports(new WebAssembly.Module(bytes)).length)
		throw new Error('WASM must have no host imports');
	await Bun.write(
		join(dir, '../src/wasm', target.embedded),
		`// Generated by wasm/build.ts; lbzip2 source and GPL license are in wasm/vendor/.\nexport const WASM_BASE64 =\n\t'${Buffer.from(bytes).toString('base64')}';\n`
	);
	await Bun.write(
		join(dir, target.manifest),
		JSON.stringify(
			{
				upstream: 'https://github.com/kjn/lbzip2',
				revision: '724352c0495904ab16e33817fae85b262f319318',
				bytes: bytes.length,
				sha256: new Bun.CryptoHasher('sha256').update(bytes).digest('hex'),
				flags: targetFlags,
				compiler,
				sourceHashes
			},
			null,
			'\t'
		) + '\n'
	);
	console.log(`Built ${target.name}: ${bytes.length} bytes of self-contained WASM`);
}
